### PR TITLE
Add ruff for python CI flow

### PR DESCRIPTION
**Pull request by grieve54706**
Add ruff for lint and format.
Add pre-commit to check lint and format.
Add action to check lint and format.

### CODE REVIEW

**Comment by goldmedal** [comment]
I changed the title to `Add ruff for python CI flow`

**Comment by goldmedal** [comment]
I found you commit a new file `ibis-server/.pre-commit-config.yaml`. Should we add it to gitignore list?

**Comment by grieve54706** [comment]
> I found you commit a new file `ibis-server/.pre-commit-config.yaml`. Should we add it to gitignore list?

No, it should be committed to repo. Every contributor should follow the rules.

**Review by goldmedal — APPROVED** [review]
Thanks @grieve54706  -- LGTM

**Pull request merged**
