### PR TITLE
feat: apache druid datasource

### PR DESCRIPTION
**Pull request by gagan-bhullar-tech**
PR closes part of [#711](https://github.com/Canner/WrenAI/issues/711)

### CODE REVIEW

**Comment by gagan-bhullar-tech** [comment]
@chilijung there is no test container available for Druid. Can you please let me know how can i add a test.

**Comment by chilijung** [comment]
@grieve54706 @goldmedal Please help provide guidance. Thanks

**Comment by grieve54706** [comment]
Hi @gagan-bhullar-tech, please follow the [development](https://github.com/Canner/wren-engine/blob/main/ibis-server/docs/development.md#getting-started) to install `pre-commit` first.
Druid provides the docker image https://hub.docker.com/r/apache/druid and the python client https://github.com/druid-io/pydruid.
You can use them to insert parquet data and query data.

**Comment by grieve54706** [comment]
We are a different repo from Wren-AI. You must use a complete URL instead of an alias for issue number.

**Comment by gagan-bhullar-tech** [comment]
@grieve54706 can you please review.

**Comment by grieve54706** [comment]
Hey @gagan-bhullar-tech, I don't see any test for ibis-server API. Please refer test suite of other data sources.

**Comment by gagan-bhullar-tech** [comment]
@grieve54706 this PR is for creating a datasource. I was thinking of creating a separate PR for API.

**Comment by grieve54706** [comment]
No, the basic creating data source should test query simply. This PR is not completed for me. And I pulled your branch then executed the test case found the table orders is not found. Because the file path is wrong and you do not mount volume for the druid container.

**Comment by grieve54706** [comment]
Close inactive PR over one month

**Pull request closed without merging**
