### PR TITLE
chore(ibis): introduce a script for query locally

### PR DESCRIPTION
**Pull request by goldmedal**
# Description
This PR implements a simple Python script to execute an SQL locally. Currently, only implement the BigQuery connection in this PR.
Given the required environment variables, we can input an SQL file like
```
poetry run python tools/query_local_run.py < test.sql
```

### CODE REVIEW

**Review by grieve54706 — COMMENTED** [review]
How about using an env var `WREN_CONFIG_ROOT` and using fixed file names like `manifest.json`, `function_list`, `connection_info.json`?

**Comment by goldmedal** [comment]
> How about using an env var `WREN_CONFIG_ROOT` and using fixed file names like `manifest.json`, `function_list`, `connection_info.json`?

In my use case, I won't put them in the same folder. I could get the manifest from another project and the function list from the ibis resource. I think it's more flexible.

**Comment by goldmedal** [comment]
Because I also use `dotenv` in this script, the user can maintain all of themin the `.env` file.

**Comment by grieve54706** [comment]
How about a `config.properties` file to collect these variables? There are too many environment variables for me now.

**Comment by goldmedal** [comment]
> How about a `config.properties` file to collect these variables? There are too many environment variables for me now.

hmm.. I think it is just a script for testing locally, not for production. I don't prefer to have an additional config file for it. Why not just use `.env` file to maintain them?

**Comment by grieve54706** [comment]
Oh! cool. The `.env` is fine to me. I didn't catch that you meant that before.

**Review by grieve54706 — APPROVED** [review]

**Comment by goldmedal** [comment]
Thanks @grieve54706

**Pull request merged**
